### PR TITLE
Add consumer proguard rules for sandwich module

### PR DESCRIPTION
**Pull request by skydoves**
Add consumer prguard rules for sandwich module.

### CODE REVIEW

**Comment by teobaranga** [comment]
Hi @skydoves, would you be able to double check this please? I think the proguard file hasn't actually been included in the final aar, at least when looking at https://mvnrepository.com/artifact/com.github.skydoves/sandwich-android/2.0.3.

**Comment by skydoves** [comment]
Hey @teobaranga, is there any way to check if the package contains a proguard rule on the website that you provided? I just added some proguard rules explicitly, and it's available with `2.0.4-SNAPSHOT`. I believe it should work well now.

**Comment by teobaranga** [comment]
There is, you should be able to see the proguard file inside the aar package available from maven. For example, the latest timber aar has a proguard.txt file in there https://mvnrepository.com/artifact/com.jakewharton.timber/timber/5.0.1. Thanks a lot for looking into this :+1:

**Comment by skydoves** [comment]
Hey @teobaranga, I just checked the AAR file for the latest version of Sandwich, and as you mentioned, it doesn't contain proguard rules. I discovered that the proguard rules should be placed in the root folder of the KMM structure, and this will be addressed in the next release. Thanks a lot for bringing this to my attention! ❤️

**Pull request merged**
