### PR TITLE
AGP 8.0 & Gradle 8.1

### PR DESCRIPTION
**Pull request by Goooler**
### 🎯 Goal
- AGP 8.0
- Gradle 8.1
- Kotlin 1.8.20
- Dsl changes.

### 🛠 Implementation details
Describe the implementation details for this Pull Request.

### ✍️ Explain examples
Explain examples with code for these updates.

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```bash
$ ./gradlew spotlessApply
```

Then dump binary APIs of this library that is public in sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that makes this change binary incompatible.

```bash
./gradlew apiDump
```

Please correct any failures before requesting a review.

## Code reviews
All submissions, including submissions by project members, require review. We use GitHub pull requests for this purpose. Consult [GitHub Help](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for more information on using pull requests.

### CODE REVIEW

**Review by skydoves — COMMENTED** [review]
Hey @Goooler, nice to meet you! 👋 
Thanks for your contribution and looks good to me.
I see the CI configuration requires Java 17 according to the error message below:

```
Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
```

**Comment by Goooler** [comment]
Noticed that too, just polished the CI.

**Review by skydoves — APPROVED** [review]
Awesome. Thanks for your contribution, @Goooler!

**Comment by skydoves** [comment]
This update will be available on SNAPSHOT.

**Comment by skydoves** [comment]
Hey @Goooler, Since merging this PR, the publication script is facing an error about `generateMetadataFileForReleasePublication`: https://github.com/skydoves/sandwich/actions/runs/4769237431/jobs/8479418913.

Do you have any idea?

**Comment by Goooler** [comment]
Very busy for days, I'll take a look tonight.

**Pull request merged**
